language: shell
before_script:
- |
  if ! git describe --exact-match --tags HEAD &> /dev/null
  then
    echo "Not a tagged release, not deploying."
    exit
  fi
- cp config.example config
- sudo apt-get -y install quilt
- sudo apt-get -y install qemu-user-static
- sudo apt-get -y install debootstrap
- sudo apt-get -y install qemu-utils
- sudo apt-get -y install kpartx
- sudo apt-get -y install pigz
- sudo apt-get -y install libarchive-tools
script:
- "sudo ./build.sh"
deploy:
  provider: releases
  api_key:
    secure: LCOtqXO4zazwRbtYxqFkxataB7nH68bPX9w4oKzHkZ1uHy2NIjCdLGREGfzcRClg035Lwk/7oUyyWianDfZzriOijBjwj4B4xsYZAKuPz07GOmF6akoe7ejMY47OqI3j3WP9Bl5lQ58T3uIfAkvphrqSI2j8Wdf0QV6KZx5Pz/xayOSCaCal//UvrDhzIzoQ71l/EanW2aS1Sp2SlHe1A3uvahHUS78vOgDMaf+rpHibvh4d/3XsGCHxHtuzQNqrIq7lqnc5vMJzVjQ6rgLSUYH4Ec31JUhJOgCO1YHl2VVs+OmeOYIiyQWkGkinttx6wpC0o+NPqqm1AtgUvqIlmTTiqkimQ7uRpwO2tNt9swMfh5qVcJ5P2Jom8mftpi0tHZrS/xP0mYdYutYag/AGnbrEvlY1DQYejeFB/VMxXwOTGC0nQ1WvUO4AwmBaiZKSJq11xpyuzN/DjQvRZKWQYScBpIVZP0J4k1HjV0fgyAG1SAW2Vtb2ID5tuqwxN6PMbHRhwhZIlyu2I4DuZfKKZVDlum/68Kt2dOX5NkUAGnSm+qj6s19PPaij/fjbTJ7hvPP+eZiK/cC1vSvDuUWkrM6jNgpaOslGQKZ8n1KAuFB5do6yqvINT43ZNndAVb8xwkrWM+8u4OJWcq+4FIlaUvfQYQegbei+of1l2zujCqo=
  edge: true
  on:
    all_branches: true
    tags: true
  file: deploy/image_`date +"%Y-%m-%d"`-Transistor-lite.zip
