language: shell
services:
- docker
before_script:
- |
  if ! git describe --exact-match --tags HEAD &> /dev/null
  then
    echo "Not a tagged release, not deploying."
    exit
  fi
- cp config.example config
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
- travis_wait "./build-docker.sh"
deploy:
  provider: releases
  api_key:
    secure: LCOtqXO4zazwRbtYxqFkxataB7nH68bPX9w4oKzHkZ1uHy2NIjCdLGREGfzcRClg035Lwk/7oUyyWianDfZzriOijBjwj4B4xsYZAKuPz07GOmF6akoe7ejMY47OqI3j3WP9Bl5lQ58T3uIfAkvphrqSI2j8Wdf0QV6KZx5Pz/xayOSCaCal//UvrDhzIzoQ71l/EanW2aS1Sp2SlHe1A3uvahHUS78vOgDMaf+rpHibvh4d/3XsGCHxHtuzQNqrIq7lqnc5vMJzVjQ6rgLSUYH4Ec31JUhJOgCO1YHl2VVs+OmeOYIiyQWkGkinttx6wpC0o+NPqqm1AtgUvqIlmTTiqkimQ7uRpwO2tNt9swMfh5qVcJ5P2Jom8mftpi0tHZrS/xP0mYdYutYag/AGnbrEvlY1DQYejeFB/VMxXwOTGC0nQ1WvUO4AwmBaiZKSJq11xpyuzN/DjQvRZKWQYScBpIVZP0J4k1HjV0fgyAG1SAW2Vtb2ID5tuqwxN6PMbHRhwhZIlyu2I4DuZfKKZVDlum/68Kt2dOX5NkUAGnSm+qj6s19PPaij/fjbTJ7hvPP+eZiK/cC1vSvDuUWkrM6jNgpaOslGQKZ8n1KAuFB5do6yqvINT43ZNndAVb8xwkrWM+8u4OJWcq+4FIlaUvfQYQegbei+of1l2zujCqo=
  edge: true
  on:
    all_branches: true
    tags: true
  file: deploy/image_`date +"%Y-%m-%d"`-Transistor-lite.zip
env:
  global:
  - secure: i+FXYnykjOSIR8pF1lnjjykUu4EoLnCUmq3A8rAv33G1uhF3yI+CCpglXgZacV7/sz6l2h56ydy9TQEk1Iijve067zo/FRRxD5wkP0DCZxAUb1ZPBNf2L80fCK7hK4f0t1JwTQ4DEerjN6CQ2hH9793ir62bXZXY+YxUsx/HYTyP3OA1ObFtqk3pQLOl6V764L7qLbRAdoWmD6bjHW1XT2XbURivQebIHHcRhy1ycwPKVCqI+XYUEr2R9OnMqZJ6oVVChQPpiqtZKUfHXabbJc7D8FL/0pFtVU1wRvBeK/t1E0if2WLp8sH+fbkOCyze+yBy2P/fpAKsWhzk/48xVQFicGmE0Y+s8XoexSSkr7OQAQjiVzfoN/C8Y2inB0gDiE9ws7cqi0zscHlz6FauCEYAy7lMqWDa/RkRkzsZ2oNn1w06WIdDmU62qW/W3GYxELtaJF6PTljThCh2jQEQq3OxmDSqCagaD1amAZ4qSxYDN3wPnub7TgxaMazQqbIukIUKJ4mZ07C+FSvicau97frOZGAKoGSv9t4mDSP/NCO9zFLFAkyZQ52YMSVaBfQ8F/2nbTDLvQ9xT/vGC7KRW9ZLaUIOlI9XmjmaEhfZLqYfnlOQNKPOB7Y7f4MiVSc4/HkcDyT56yWlK86oM1UnZzMVtrGxWGSaCNPyxDTTp7k=
  - secure: Jc2e8VoLbOycoS1IXfUj2xceHEtmBRm+GCAn8SzPvDfVpmQ6EcDeYyS1Fv61daaqr07vMm+bmPO9KPGW/8Spobx4ZJY/ttAlP8BWuhknc5TNkv5cfosbEdgS3w4mBZw9pn2IOrXqN8RrxiHe1TMmDtj+Zok5klvX///aL6RiHazoY2GnQSzmp+lxrhQjpVoia+PXbHuH8Ei10Zn4Wc0FWPLtJSsJjbzh5/ypIq14EnyWiDOTpMxcbx8tOcdCdIArV8OIWEsBjsmcGT6dzJys9+m6jisQw4p5od6HcroUQKZTLNLwKCD6RQo7D+5r/bY+AWu+HeRPanqDARDeS/3M/6WGCMMVz93QA4g8S8UpmR6Syib93DDBgR5j7v/t/mXaFmsJt8An9NELRvV5E6IMpF2Y+W3s/Xup8wW3Eog8ZN5Y/ZwI5UCyx7EbuaHrDnPbs/z88T0Idy7Ejo0wdrKXw9qeHeFP1RLNaysj4z+Q7iuV1DUTXshX571LGAdW2ulpm6Q1Uk87qE2+XtVO/FAb0H+/n0JQRv/ryIATlP+zAD9iBygCuRHZbSexp6iHQe97ELBJZBBBAsp32RgBgalKMnbN50cVF3QRlnZ8IVypApwXdlgS/+d6zR46YsJ2HwBR7BkVs2jOvvNouOW7J6I+29SFlJBzr7gtkxGUX5DVLr4=
