# Generated by Django 3.2.6 on 2022-01-04 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subscribe_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('link', models.URLField(blank=True)),
                ('max_entries', models.PositiveSmallIntegerField(default=3, verbose_name='Number of episodes to keep')),
                ('image', models.URLField(blank=True)),
                ('fs_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('link', models.URLField()),
                ('audio', models.URLField(blank=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.feed')),
            ],
        ),
    ]
